# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "turing/ROOT/nixos-18.09";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0BD8-9898";
      fsType = "vfat";
    };

  fileSystems."/tmp" =
    { device = "turing/ROOT/tmp";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "gauss/home";
      fsType = "zfs";
    };

  fileSystems."/var/lib/docker" =
    { device = "gauss/var/lib/docker";
      fsType = "zfs";
    };

  fileSystems."/var/lib/machines" =
    { device = "gauss/var/lib/machines";
      fsType = "zfs";
    };

  fileSystems."/var/lib/libvirt/images" =
    { device = "gauss/var/lib/libvirt/images";
      fsType = "zfs";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
