# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "euler/root/nixos-20.09";
    fsType = "zfs";
  };

  fileSystems."/home/corin" = {
    device = "euler/home/corin";
    fsType = "zfs";
  };

  fileSystems."/home/corin/.cache" = {
    device = "euler/home/corin/.cache";
    fsType = "zfs";
  };

  fileSystems."/home/corin/.gem" = {
    device = "euler/home/corin/.gem";
    fsType = "zfs";
  };

  fileSystems."/home/corin/.m2" = {
    device = "euler/home/corin/.m2";
    fsType = "zfs";
  };

  fileSystems."/home/corin/.npm" = {
    device = "euler/home/corin/.npm";
    fsType = "zfs";
  };

  fileSystems."/home/corin/.qemu" = {
    device = "euler/home/corin/.qemu";
    fsType = "zfs";
  };

  fileSystems."/home/corin/.vim/swapfiles" = {
    device = "euler/home/corin/.vim/swapfiles";
    fsType = "zfs";
  };

  fileSystems."/home/corin/Downloads" = {
    device = "euler/home/corin/Downloads";
    fsType = "zfs";
  };

  fileSystems."/home/corin/src" = {
    device = "euler/home/corin/src";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "euler/nix";
    fsType = "zfs";
  };

  fileSystems."/usr/lib/node_modules" = {
    device = "euler/usr/lib/node_modules";
    fsType = "zfs";
  };

  fileSystems."/usr/local" = {
    device = "euler/usr/local";
    fsType = "zfs";
  };

  fileSystems."/usr/src" = {
    device = "euler/usr/src";
    fsType = "zfs";
  };

  fileSystems."/var/db" =
    { device = "euler/var/db";
      fsType = "zfs";
    };

  fileSystems."/var/lib/docker" = {
    device = "euler/var/lib/docker";
    fsType = "zfs";
  };

  fileSystems."/var/lib/libvirt" = {
    device = "euler/var/lib/libvirt";
    fsType = "zfs";
  };

  fileSystems."/var/lib/libvirt/images" = {
    device = "euler/var/lib/libvirt/images";
    fsType = "zfs";
  };

  fileSystems."/var/lib/machines" = {
    device = "euler/var/lib/machines";
    fsType = "zfs";
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2EE2-3725";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5ac8cdaf-6aea-4a20-9335-e59f8ad4f369"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
